Project Scenario:

An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF).

The required data seems to be available on the URL mentioned below:

URL: https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29Project Scenario:
An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF).

The required data seems to be available on the URL mentioned below:

URL: https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29

Objectives

After completing this lab you will be able to:

Use Webscraping to extract required information from a website.
Use Pandas to load and process the tabular data as a dataframe.
Use Numpy to manipulate the information contatined in the dataframe.
Load the updated dataframe to CSV file.

In [1]:
#!pip install lxml

In [3]:
import pandas as pd
import numpy as np

def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

In [4]:
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

In [5]:
tables = pd.read_html(URL)

In [6]:
df= tables[3]

In [7]:
df.columns = range(df.shape[1])

In [8]:
df = df[[0,2]]

In [9]:
df = df.iloc[1:11,:]

In [10]:
df.columns = ['Country','GDP (Million USD)']

In [11]:
df

           Country GDP (Million USD)
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

In [12]:
df.dtypes

Country              object
GDP (Million USD)    object
dtype: object

In [13]:
df['GDP (Million USD)'] = df['GDP (Million USD)'].astype(int)

In [14]:
df[['GDP (Million USD)']] = df[['GDP (Million USD)']]/1000

In [15]:
df[['GDP (Million USD)']] = np.round(df[['GDP (Million USD)']],2)

In [16]:
df.rename(columns = {'GDP (Million USD)':'GDP (Billion USD)'})

           Country  GDP (Billion USD)
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [17]:
df.to_csv('./Largest_economies.csv')